# Generated by Django 5.2 on 2025-04-04 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(default='', limit_choices_to={'role': 'Seller'}, on_delete=django.db.models.deletion.CASCADE, to='myapp.login'),
        ),
    ]
